lb1_initial_angle: '73'
lb2_initial_angle: '46'
lb3_initial_angle: '75'
lf1_initial_angle: '73'
lf2_initial_angle: '52'
lf3_initial_angle: '83'
rb1_initial_angle: '71'
rb2_initial_angle: '147'
rb3_initial_angle: '60'
rf1_initial_angle: '90'
rf2_initial_angle: '138'
rf3_initial_angle: '73'
