left_front:
  - LF1_JOINT
  - LF2_JOINT
  - LF3_JOINT
  - LF4_JOINT

right_front:
  - RF1_JOINT
  - RF2_JOINT
  - RF3_JOINT
  - RF4_JOINT

left_hind:
  - LB1_JOINT
  - LB2_JOINT
  - LB3_JOINT
  - LB4_JOINT

right_hind:
  - RB1_JOINT
  - RB2_JOINT
  - RB3_JOINT
  - RB4_JOINT